image: gcc:latest

stages:
   - build
   - test

.install-dependencies:
   before_script:
      - apt-get update
      - apt-get install -y cmake make gcovr

compile-firmware:
   stage: build
   image: nordicplayground/nrfconnect-sdk:main
   script: "./scripts/build.sh"
   artifacts:
      untracked: true
      paths:
         - build/zephyr/*.bin
         - build/zephyr/*.elf
         - build/zephyr/*.hex

compile-test:
   stage: build
   extends: .install-dependencies
   script: "./scripts/build-test.sh"
   artifacts:
      untracked: true
      paths:
         - build/

test-chess_logic:
   stage: test
   needs:
      - job: compile-test
        artifacts: true
   dependencies:
      - compile-test
   script: "./scripts/test-xml.sh"
   artifacts:
      reports:
         junit: test-results.xml

coverage-chess_logic:
   stage: test
   needs:
      - job: compile-test
        artifacts: true
   dependencies:
      - compile-test
   extends: .install-dependencies
   script: "./scripts/coverage.sh"
   artifacts:
      reports:
         coverage_report:
            coverage_format: cobertura
            path: coverage.xml
