image: gcc:latest

stages:
   - build
   - test

.install-dependencies:
   before_script:
      - apt-get update
      - apt-get install -y cmake make gcovr

compile-firmware:
   stage: build
   image:
      name: registry.gitlab.com/projekt-inzynierski-uken/firmware/nrfconnect-sdk:latest
   before_script:
      - chmod +x ./scripts/init.sh ./scripts/build.sh
      - ./scripts/init.sh
      - export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
      - export ZEPHYR_BASE=$(pwd)/external/zephyr
      - export ZEPHYR_GCC_VARIANT=cross-compile
   script: "./scripts/build.sh"
   artifacts:
      untracked: true
      paths:
         - build/zephyr/*.bin
         - build/zephyr/*.elf
         - build/zephyr/*.hex

compile-test:
   stage: build
   extends: .install-dependencies
   script: "./scripts/build-test.sh"
   artifacts:
      untracked: true
      paths:
         - build/

test-chess_logic:
   stage: test
   needs:
      - job: compile-test
        artifacts: true
   dependencies:
      - compile-test
   script: "./scripts/test-xml.sh"
   artifacts:
      reports:
         junit: test-results.xml

coverage-chess_logic:
   stage: test
   needs:
      - job: compile-test
        artifacts: true
   dependencies:
      - compile-test
   extends: .install-dependencies
   script: "./scripts/coverage.sh"
   artifacts:
      reports:
         coverage_report:
            coverage_format: cobertura
            path: coverage.xml
