CONFIG_PM_PARTITION_SIZE_MCUBOOT=0x20000
CONFIG_SIZE_OPTIMIZATIONS=y

CONFIG_BOOT_SIGNATURE_TYPE_RSA=y
CONFIG_BOOT_SIGNATURE_TYPE_RSA_LEN=2048

CONFIG_BOOT_BANNER=y
CONFIG_MCUBOOT_INDICATION_LED=y
CONFIG_BOOT_MAX_IMG_SECTORS=512

CONFIG_MULTITHREADING=y

CONFIG_LVGL=n
CONFIG_ADC=y
CONFIG_I2C=n
CONFIG_SPI=n
CONFIG_GPIO=y
CONFIG_SHELL=y
CONFIG_FPROTECT=y
CONFIG_DISABLE_FLASH_PATCH=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_FLASH=y

CONFIG_LOG=y
CONFIG_MCUBOOT_LOG_LEVEL_DBG=y
