CONFIG_CPP=y
CONFIG_GLIBCXX_LIBCPP=y

#CONFIG_CHESS_LOGIC=y

# LVGL
CONFIG_LVGL=y
CONFIG_LV_USE_LOG=y
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_COLOR_16_SWAP=y
CONFIG_LV_Z_BITS_PER_PIXEL=16
CONFIG_LV_Z_BUFFER_ALLOC_STATIC=y
